StoreApp/Components/ProductSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _serviceManager;

        public ProductSummaryViewComponent(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public String Invoke()
        {
            var productsCount = _serviceManager.ProductService.GetAllProducts(false).Count();
            return productsCount.ToString();
        }

        // public IViewComponentResult Invoke()
        // {
        //     var productsCount = _manager.ProductService.GetAllProducts(false).Count();
        //     return View("Default", productsCount);
        // }
    }
}

StoreApp/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {

        private IServiceManager _manager;

        public CategoryController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            List<Category> categories = _manager.CategoryService.GetAllCategories(false).ToList();
            return View(categories);
        }
    }
}

StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {

        private readonly IServiceManager _manager;
        private readonly Cart _cart;

        public OrderController(IServiceManager serviceManager, Cart cart)
        {
            _manager = serviceManager;
            _cart = cart;
        }

        public IActionResult Index()
        {
            return View();
        }
        public ViewResult Checkout() => View(new Order());
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order)
        {
            if (_cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                _manager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToPage("/Complete", new { OrderId = order.OrderId });
            }
            return View();
        }
    }
}

StoreApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {

        private readonly IServiceManager _manager;
        // private readonly RepositoryContext _context;

        // public ProductController(RepositoryContext context)
        // {
        //     _context = context;
        // }

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            // var _context = new RepositoryContext(new DbContextOptionsBuilder<RepositoryContext>().UseSqlite("Data Source=D:\\learning\\MVC\\ProductDB.db").Options);
            // return _context.Products.ToList();
            // Eğer DI olmazsa üstteki gibi bir kullanım yapılabilir.
            // var model = _context.Products.ToList();
            List<Product> model = _manager.ProductService.GetAllProducts(false).ToList();
            return View(model);
        }


        public IActionResult Get(int id)
        {
            // var model = _context.Products.Find(id);
            Product model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
    }
}

StoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css">
</head>

<body>

    <header>
        <partial name="_Navbar" />
        @RenderSection("Header", required: false)
    </header>
    <div class="container">

        <main role="main" class="pb-3">@RenderBody()</main>
    </div>
    <footer>
        Footer
        @RenderSection("Footer", required: false)
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
    <style src="~/lib/jquery/jquery.min.js"></style>
    <style src="~/lib/font-awesome/all.min.js"></style>
    <style src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></style>
    <style src="~/js/script.js"></style>
</body>

</html>

StoreApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Admin Panels</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Dashboard"
                        asp-action="Index">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" asp-controller="Product" asp-action="Index">Products (
                        @await Component.InvokeAsync("ProductSummary"))</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" asp-controller="Category" asp-action="Index">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" asp-controller="Order" asp-action="Index">Orders</a>
                </li>
                <li class="nav-item">
                    <a target="_blank" class="nav-link" aria-current="page" asp-area="" asp-controller="Home"
                        asp-action="Index">Ana sayfsa</a>
                </li>
            </ul>


        </div>
    </div>
</nav>